version: "3.9"
services: 
  app:
    # Build context will look into the current directory and build a docker using Dockerfile
    # Either we can specify the image or give build context
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command : >
      sh -c "python manage.py runserver 0.0.0.0:8000"

